name: sports_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  salomon_bottom_bar: ^3.3.2
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  http: ^1.2.1

  # firebase
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/focub-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/leagues/
    - assets/stadiums/
    - assets/focub-logo.png